name: Build and publish to PyPI

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build tools
        run: python -m pip install --upgrade build

      - name: Build dist
        run: python -m build

      - name: Publish (Trusted publishing via OIDC)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/